### ISSUE TITLE
load bundles from a Hive table

### ISSUE THREAD

**Issue by boristyukin** [cerner/bunsen#15]
For one of our projects, we store bundles with various resources in a Hive table. That table has several other columns, used for the various purposes. So a table looks like that:

create table fhir_extract (id bigint, col1 string, col2 string, fhir_bundle string);

fhir_bundle can contain various resources (patient, observation, encounter etc.) and resources can have both mandatory and optional elements.

I think at the moment Bunsen does not support loading of resources from a hive table column.

**Comment by boristyukin** [comment]
@rbrush thanks for a quick response, Ryan! I like your suggested approach. Ultimately we will be storing many millions of bundles and I feel Hive/HDFS is a good storage engine for that. I could store bundles as individual json files on hdfs but then it will lead to a small file problem on hdfs. I think this change will allow use massive amounts of bundles unless it is possible already by loading json as strings from Hive and then using bundles.extractresource method.

**Comment by rbrush** [comment]
Sounds good! I think we'll probably need something similar for our workloads as well, so I'll try to find time to add this in the next couple days. I'll post back here with updates.

**Comment by boristyukin** [comment]
awesome!! if it is not too much to ask, I think you created a separate branch for spark 2.2 earlier - not sure if Bunsen has moved to 2.2 yet. If not, would be great if you can push a version with 2.2. Oh and I am using Pyspark, hopefully your suggested wrappers will be available as well :)

**Comment by rbrush** [comment]
I do have good news on Spark 2.2: we released support for it in Bunsen 0.2.x, which is available now. 

I should have updated that other thread to reflect that, but we're going keeping a compatibility matrix here: http://engineering.cerner.com/bunsen/

**Comment by rbrush** [comment]
Alright, I took a pass at this in pull request #16. 

@boristyukin, let me know if this looks helpful (or even checkout the issue-15 branch and take it for a spin with a local build if you would like.)

**Comment by boristyukin** [comment]
@rbrush man you rock! we will try to test it shortly. Are there any special instructions to build the project locally with Maven and run the tests? We will use also some real bundles from our vendor who just switched to STU3

**Comment by rbrush** [comment]
@boristyukin Thanks! 

The only special steps to build are the Python tests require Spark 2.2 and Python 3.5+ installed on the build machine (although we're working on eliminating that need). However, you can skip the Python tests with the following command to create a full build:

mvn clean install -Dskip.python.tests=true

Once built, you'll just want to add Bunsen code to your PYTHON path and the shaded JAR to spark similar to what is shown here:

http://engineering.cerner.com/bunsen/introduction.html

**Comment by boristyukin** [comment]
@rbrush can you clarify if we need Python 3.5 just to run the tests or build bunsen? We use 2.7 on our cluster

**Comment by rbrush** [comment]
@boristyukin So far we've built and tested exclusively on Python 3.5, so I doubt it will work with Python 2.7 as it stands today. That said, I think all of our dependencies work on 2.7 so we can probably make this work. I might have a chance to play around with this later in the week, or you're welcome to give it a shot if you'd like as well and we can work in any needed changes.

**Comment by rbrush** [comment]
It looks like we might be fine with Python 2.7 after all. On a whim I Bunsen's tests in a Python 2.7 environment and everything passed. I don't have a Hadoop/Spark cluster with Python 2.7 handy to thoroughly test this, but the py.tests suggest it will work.

**Comment by boristyukin** [comment]
Thanks Ryan. I was hoping 2.7 would work. We are setting things up to
compile bunsen locally.

**Comment by boristyukin** [comment]
@rbrush  great news - it worked fine with Python 2.7. from_json works like a charm so far! I will do more testing using our vendor's bundles but the first batch of 70 bundles, loaded to Hive, worked fine. My table was using AVRO and I forgot Spark does not support it. Once I converted it to Parquet, bunsen happily extracted resources from my Hive table. I also loved save_to_database feature - this will be really handy.

**Comment by rbrush** [comment]
Great, I'm glad it works! I'll go ahead and merge these changes into master since everything is passing in our test environment as well.

**Comment by rbrush** [comment]
This has been merged and looks to be working well in our tests and a real environment, so I'm going to go ahead and close this issue. We can create another issue if any problems pop up.

We can also push out a 0.2.3 release without too much trouble if that would be helpful.
