### ISSUE TITLE
Uplift for Spark 2.4.0

### ISSUE THREAD

**Issue by bdrillard** [cerner/bunsen#47]
Spark 2.4.0 is available now and we should uplift Bunsen to use this latest, stable version.

**Comment by LaRiffle** [comment]
@bdrillard @rbrush any news on a possible uplift?

**Comment by munavvar20** [comment]
I see that PR is merged for this and the issue is closed. Any ETA on when new release will be made available?

**Comment by bdrillard** [comment]
Thanks for the follow-up. A new release was cut shortly after the merge, `0.4.9`.
