### ISSUE TITLE
[0.5.0-Dev] Avro Schema generation for fields of "Element" type are not expanded

### ISSUE THREAD

**Issue by amarvakul** [cerner/bunsen#63]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
Avro Schema for fields of "Element" type doesn't include all the specialized items defined in the corresponding profile. E.g., for "Timing" [1] data-type, the avro schema doesn't include all the children for "repeat" element such as _count_, _bounds_ etc., instead its defined as base _Element_ type.

[1] https://www.hl7.org/fhir/datatypes.html#Timing

### Expected Outcomes
- If a field of type "Element" is encountered, the corresponding schema should be defined as a specialized type that includes all the children.

**Comment by bdrillard** [comment]
Closed by #64
