### ISSUE TITLE
[0.5.0-Dev] type cast exception while converting from hapi object to avro specific record

### ISSUE THREAD

**Issue by amarvakul** [cerner/bunsen#66]
Please fill out the below template as best you can.
--------------------------------------------------------

### Description of Issue
Following exception is thrown while converting a HAPI object that has contained resource to an Avro SpecificRecord object

`Caused by: java.lang.ClassCastException: com.cerner.bunsen.stu3.avro.Provenance cannot be cast to org.apache.avro.generic.GenericData$RecordCaused by: java.lang.ClassCastException: com.cerner.bunsen.stu3.avro.Provenance cannot be cast to org.apache.avro.generic.GenericData$Record at com.cerner.bunsen.avro.converters.DefinitionToAvroVisitor$HapiContainedToAvroConverter.createContained(DefinitionToAvroVisitor.java:258) at com.cerner.bunsen.definitions.HapiContainedConverter.fromHapi(HapiContainedConverter.java:113) at com.cerner.bunsen.definitions.HapiCompositeConverter.fromHapi(HapiCompositeConverter.java:190) at com.cerner.bunsen.avro.AvroConverter.resourceToAvro(AvroConverter.java:173) at `

**Comment by bdrillard** [comment]
Closed by #67
